Repository searxng/searxng, pull requests merged in 2024-02, with the labels that each got.

#3000 [feat] engine: implementation of brave goggles
  AUTHORS.rst
  searx/engines/brave.py
  searx/settings.yml
Labels: preview-environment-commented

#3207 [feat] engine: implementation of mozhi
  searx/engines/mozhi.py
  searx/settings.yml
Labels: preview-environment-commented

#3045 Setup.py: fix infopage location
  setup.py
Labels: NixOS

#3237 [fix] opensearch.xml: firefox v123 does not except self-URI (URL with param)
  searx/templates/simple/opensearch.xml
  searx/webapp.py
Labels: opensearch
